services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        env_file:
            - ./docker/.env.docker
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lms
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
